### ISSUE TITLE
Are there any plan to include/complete the Questionnaire model?

### ISSUE THREAD

**Issue by rafen** [aristotle-mdr/mallard-questionnaire-registry#8]
I noticed that in the `models.py` file the `Questionnaire` and `QuestionModule` models are commented:
https://github.com/aristotle-mdr/mallard-questionnaire-registry/blob/516614b740a66eb14e0950d9db9927bb2620c232/mallard_qr/models.py#L56

is there any special reason why those models are not in the app?
do you have any suggestion/recommendation of how to implement those? (we are planning to implement a similar functionality, and it would be nice to contribute to Aristotle project)

Thanks!

**Comment by LegoStormtroopr** [comment]
That was prototype work, that is still underdevelopment.

All Aristotle metamodel objects need (or should) have a reference standard they are implementing and it has been difficult finding an appropriate standard for questionnaires. The best so far is the GSIM Question module area.

There is some other interest in this conceptual area, so I may have to make a decision soon.

**Comment by rafen** [comment]
Thanks for the feedback!
Can you please provide me a link for the "GSIM Question module area" I would like to research more about it, and see if we can build our new functionality while we contribute to Aristotle.


Thanks!

**Comment by LegoStormtroopr** [comment]
Its hard to link within the UN site, but the spec is here: https://statswiki.unece.org/display/metis/Generic+Statistical+Information+Model

**Comment by rafen** [comment]
Thank you! I'm closing this issue.
